### Recuperar todos los empleados
GET http://localhost:12348/empleados

### Recuperar un empleado por iduniqemp
GET http://localhost:12348/empleados/1

### Recuperar todos los empleados por una area
GET http://localhost:12348/empleados?area=Legal

### Crear un empleado de la organización
POST https://o8osixauuc.execute-api.us-east-1.amazonaws.com/dev/empleados
Content-Type: application/json

{
  "id_cargo": 3,
  "nombre": "Diego",
  "apellidos": "Maradona",
  "username": "dmaradona",
  "email": "maradona.d@example.com",
  "fecha_nacimiento": "1960-10-30T00:00:00.000Z",
  "fecha_ingreso": "2023-09-15T00:00:00.000Z",
  "residencia": "Avenida Siempre Viva",
  "ciudad_residencia": "Buenos Aires",
  "estrato": 5,
  "activo": true
}

### Actualizar un empleado
PATCH http://localhost:12348/empleados/1
Content-Type: application/json

{
  "nombre": "Camilo Actualizado",
  "ciudad_residencia": "Cali",
  "activo": false
}

### Eliminar un empleado
DELETE http://localhost:12348/empleados/5

### Subir una imagen de perfil de un empleado
POST http://localhost:12348/empleados/1/upload
Content-Type: multipart/form-data

File: {imagen.jpg} // Selecciona un archivo desde tu cliente (Postman/Insomnia).

### Subir un archivo medico del empleado
POST http://localhost:12348/empleados/5/upload/medical
Content-Type: multipart/form-data

File: {examen_medico.pdf} // Archivo de examen médico en el campo "file"

### Obtener una imagen de un empleado
GET http://localhost:12348/empleados/5/profile-image

### Obtener un documento registro medico de un empleado
GET http://localhost:12348/empleados/5/medical-records/registro_medico_2024.pdf

### Actualizar otro empleado
{
  "email": "ana.gomez@update.com",
  "activo": false
}

### Subir una imagen con REST Client
POST http://localhost:12348/empleados/1/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="imagen.jpg"
Content-Type: image/jpeg

< ./Users/camilofalla/Documents/developer/fullstack/proyecto_poli/rest-api-deploy/data/images/imagen.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### PRUEBAS CON EL BACKEND EC2 DESPLEGADO

### Recuperar un empleado por iduniqemp
GET http://3.88.209.44:12348/empleados/